/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csc733.group5;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;

public class App {

    public static final Driver startDriver() {
        return GraphDatabase.driver("bolt://localhost:7687",
                AuthTokens.basic("neo4j", "secret"));
    }
}
